# Generated by Django 4.2.5 on 2023-09-13 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_firm_position_remove_firmuser_test_firmuser_firm_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="position",
            old_name="firm_name",
            new_name="position",
        ),
    ]
