# Generated by Django 4.2.5 on 2023-09-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="casestage",
            name="stage",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="casetype",
            name="type",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="court",
            name="court",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
