# Generated by Django 4.2.5 on 2023-09-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0003_alter_cases_appearing_lawyer_alter_cases_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestage",
            name="stage",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="casetype",
            name="type",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="court",
            name="court",
            field=models.CharField(max_length=60),
        ),
    ]
