# Generated by Django 4.2.5 on 2023-09-12 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="casestage",
            old_name="type",
            new_name="stage",
        ),
        migrations.RenameField(
            model_name="court",
            old_name="type",
            new_name="court",
        ),
    ]
